### ISSUE TITLE
Toolkit v6 - Roadmap & Breaking discussion

### ISSUE THREAD

**Issue by Antonio-Laguna** [10up/10up-toolkit#266]
Given we don't encourage Browsersync anymore but was kept for backwards compatibility I'm wondering if we should use upcoming 5.0.0 as an occasion to actually remove this option and get the package leaner itself.

If so, is there anything else we could consider to introduce that's breaking? 

I wonder this since we want to be stable and don't break but there are instances in which we need to so let's use those to remove legacy and discouraged processes.

Maybe we should enforce useBlocks now?

Thoughts @nicholasio & @fabiankaegy 

UPDATE with list of breaking changes and rollout tasks

**Breaking Changes**
- [x] #325 
- [x] #284
- [x]  #326
- [ ]  #327

**Other Changes**
- [x] #302 
- [x] #323 
- [x]  postcss-editor-styles: Move to antonio's fork

**Rollout Plan**
- [x] [Internal] Blog Post announcing upcoming breaking changes.
- [x] Release v6 in the next branch and ask for testers

**Comment by nicholasio** [comment]
I agree it's about time to remove browser sync.

Regarding `useBlocks` I think we can make it the default option in 5.0 but still give the option to preserve the current default behavior.

**Comment by Antonio-Laguna** [comment]
@fabiankaegy do you think we could get rid of this too? 

https://github.com/10up/10up-toolkit/blob/develop/packages/toolkit/config/postcss.config.js#L18

**Comment by fabiankaegy** [comment]
Thanks for starting this discussion :) 

And yeah I think it is time to make the `useBlockAssets` feature flag the default behavior. But I will add that I have only ever used toolkit for WordPress related projects. And whilst I don't _think_ that it would have any effect on anything outside of that we should make sure that it was tested with such projects.

> @fabiankaegy do you think we could get rid of this too?
>
>https://github.com/10up/10up-toolkit/blob/develop/packages/toolkit/config/postcss.config.js#L18

Yeah I'd love to remove this handling and even the need for the editor styles scoping post CSS plugin altogether

**Comment by nicholasio** [comment]
Also wanted to bring this to the table https://github.com/10up/10up-toolkit/issues/297

**Comment by nicholasio** [comment]
Updated issue description with breaking changes for next major and rolloup plan
